@Restaurants.API_HostAddress = https://localhost:7204
@token = CfDJ8PZ2vdBObfBFlpHBTLGwyaVBJvx3Z_x3pXXw



GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###


GET {{Restaurants.API_HostAddress}}/api/restaurants

###
